# Environment
env=QT_QPA_PLATFORMTHEME,qt6ct
env=QT_WAYLAND_FORCE_DPI,120
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_QPA_PLATFORM,Wayland;xcb

# Autostart
exec-once = echo "Xft.dpi: 144" | xrdb -merge
exec-once = /usr/libexec/xdg-desktop-portal &
exec-once = /usr/libexec/xdg-desktop-portal-wlr &
exec-once = noctalia

# Input
xkb_rules_options=caps:swapescape
drag_tile_to_tile=1
trackpad_natural_scrolling=1

# Window Rules
windowrule=isnamedscratchpad:1,appid:dev.noctalia.Noctalia,width:1536,height:935
windowrule=isnamedscratchpad:1,appid:org.ghostty.scratchpad,width:1536,height:935

source=~/.config/mango/layout.conf
source=~/.config/mango/animations.conf
source=~/.config/mango/noctalia.conf
source=~/.config/mango/appearance.conf
source=~/.config/mango/binds.conf
