animation_duration_move=250
animation_duration_tag=250
animation_duration_open=250
animation_duration_close=250
animation_curve_move=0.16,1.0,0.3,1.0
animation_curve_open=0.16,1.0,0.3,1.0
animation_curve_tag=0.16,1.0,0.3,1.0
animation_curve_close=0.16,1.0,0.3,1.0
animation_curve_focus=0.16,1.0,0.3,1.0
animation_curve_opafadein=0.16,1.0,0.3,1.0
animation_curve_opafadeout=0.16,1.0,0.3,1.0
